#!/usr/bin/env node
// build.js — Generate config.js from environment variables for Vercel deployment
// Runs at build time; injects VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY into config.js

const fs = require('fs');
const path = require('path');

const supabaseUrl = process.env.VITE_SUPABASE_URL;
const supabaseAnonKey = process.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  console.error('❌ Build failed: missing environment variables');
  console.error('   Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in Vercel dashboard');
  process.exit(1);
}

const configContent = `// ── webcap config (generated by build.js) ───────────────────────────────
// This file is generated at build time from environment variables.
// Never commit — it's in .gitignore

window.SUPABASE_URL      = '${supabaseUrl}';
window.SUPABASE_ANON_KEY = '${supabaseAnonKey}';
`;

const configPath = path.join(__dirname, 'config.js');
fs.writeFileSync(configPath, configContent, 'utf8');

console.log('✓ Generated config.js from environment variables');
