#!/usr/bin/env node
// DEPRECATED — build.js is no longer used
//
// Historical context: This script previously generated config.js at build time.
//
// Current approach (as of May 2026):
// - Supabase config is fetched from /api/config serverless function
// - Config endpoint reads from Vercel environment variables
// - No build step or generated files needed
//
// To re-enable this script, update Vercel build settings to run:
//   node build.js
// And set Vercel environment variables:
//   VITE_SUPABASE_URL = your-supabase-url
//   VITE_SUPABASE_ANON_KEY = your-anon-key

const fs = require('fs');
const path = require('path');

const supabaseUrl = process.env.VITE_SUPABASE_URL;
const supabaseAnonKey = process.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  console.error('❌ Build failed: missing environment variables');
  console.error('   Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in Vercel dashboard');
  process.exit(1);
}

const configContent = `// ── webcap config (generated by build.js) ───────────────────────────────
// This file is generated at build time from environment variables.
// Never commit — it's in .gitignore

window.SUPABASE_URL      = '${supabaseUrl}';
window.SUPABASE_ANON_KEY = '${supabaseAnonKey}';
`;

const configPath = path.join(__dirname, 'config.js');
fs.writeFileSync(configPath, configContent, 'utf8');

console.log('✓ Generated config.js from environment variables');
